export { default as About } from './About'
export { default as Titles } from './Titles'
export { default as HomeLayout } from './HomeLayout'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Landing } from './Landing'
export { default as Profile } from './Profile'
export { default as ErrorPage } from './ErrorPage'
